name: sdkwork_terminal_flutter_mobile
description: SDKWork Terminal Flutter mobile application for iOS and Android.
publish_to: 'none'
version: 0.2.59+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^9.2.4
  sdkwork_iam_app_sdk:
    path: ../../../sdkwork-iam/sdks/sdkwork-iam-app-sdk/sdkwork-iam-app-sdk-dart/generated/server-openapi

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
